import type { ContactContent } from "../schema";

export const contact: ContactContent = {
  label: "Контакты",
  title: { lead: "Обсудим", accent: "backend-задачу" },
  description: "Рассматриваю полную занятость, стажировку и проектную работу. Готов к переезду и командировкам.",
  status: "Открыт к предложениям",
  responseTime: "Обычно отвечаю в течение дня",
  phone: "+7 (980) 389-23-83",
  phoneLabel: "Позвонить",
  email: "asmorr@yandex.ru",
  emailLabel: "Написать на email",
  github: "https://github.com/asmorr",
  githubLabel: "Посмотреть GitHub",
  location: "Санкт-Петербург, Россия",
  locationLabel: "Локация",
  form: {
    nameLabel: "Имя",
    namePlaceholder: "Как к вам обращаться",
    emailLabel: "Email для ответа",
    emailPlaceholder: "name@example.com",
    messageLabel: "Сообщение",
    messagePlaceholder: "Расскажите о задаче, команде или проекте",
    submitLabel: "Отправить сообщение",
    requiredError: "Заполните это поле",
    emailError: "Введите корректный email",
    messageLengthError: "Сообщение должно быть не длиннее 2000 символов",
    unavailableMessage: "Форма уже готова, но отправка появится позже. Пока напишите мне напрямую на email.",
  },
};
