import type { ContactContent } from "../schema";

export const contact: ContactContent = {
  label: "Контакты",
  title: { lead: "Обсудим", accent: "backend-задачу" },
  description: "Рассматриваю полную занятость, стажировку и проектную работу. Готов к переезду и командировкам.",
  form: {
    nameLabel: "Ваше имя",
    namePlaceholder: "Как к вам обращаться",
    emailLabel: "Email для ответа",
    emailPlaceholder: "you@example.com",
    messageLabel: "Сообщение",
    messagePlaceholder: "Расскажите, что хотите обсудить",
    submitLabel: "Отправить сообщение",
    sendingLabel: "Отправляем…",
    requiredError: "Заполните это поле.",
    invalidEmailError: "Введите корректный email.",
    tooLongError: "Превышена допустимая длина.",
    validationFailed: "Проверьте введённые данные и попробуйте ещё раз.",
    successMessage: "Сообщение отправлено. Спасибо!",
    deliveryError: "Не удалось отправить сообщение. Попробуйте ещё раз или напишите напрямую.",
    rateLimitError: "Слишком много попыток. Подождите немного и попробуйте снова.",
    unavailableError: "Форма временно недоступна. Напишите напрямую на email.",
  },
  status: "Открыт к предложениям",
  responseTime: "Обычно отвечаю в течение дня",
  phone: "+7 (980) 389-23-83",
  phoneLabel: "Позвонить",
  email: "asmorr@yandex.ru",
  emailLabel: "Написать на email",
  github: "https://github.com/asmorr",
  githubLabel: "Посмотреть GitHub",
  location: "Санкт-Петербург, Россия",
  locationLabel: "Локация",
};
