import type { TimelineContent } from "../schema";

export const timeline: TimelineContent = {
  label: "Путь",
  title: "Опыт и образование",
  intro: "Рабочие и учебные задачи, которые формируют мой подход к backend-разработке.",
  items: [
    {
      id: "itmo-research",
      period: "Март 2025 — сейчас",
      start: "2025-03",
      end: null,
      track: "work",
      kind: "Работа",
      organization: "ИТМО, Санкт-Петербург",
      role: "Лаборант / Backend Developer",
      description: "Начинал с базы данных и backend библиотечного фреймворка для анализа научных публикаций. С января 2026 проект объединён со смежными командами в микросервисную систему сбора, обработки и валидации данных; отвечаю за сервис эталонизации.",
      tags: [
        { label: "Сервис эталонизации", category: "contribution" },
        { label: "Python", category: "technology" },
        { label: "Микросервисы", category: "practice" },
        { label: "Научные данные", category: "domain" },
      ],
      status: "Сейчас",
    },
    {
      id: "lkey",
      period: "Декабрь 2024 — май 2025",
      start: "2024-12",
      end: "2025-05",
      track: "work",
      kind: "Проектная работа",
      organization: "Lkey Studio",
      role: "Backend Developer",
      description: "С нуля спроектировал серверную архитектуру интернет-магазина осветительных приборов: REST API, модель данных и слой кэширования.",
      tags: [
        { label: "Архитектура с нуля", category: "contribution" },
        { label: "Django REST Framework", category: "technology" },
        { label: "PostgreSQL", category: "technology" },
        { label: "Redis", category: "technology" },
      ],
    },
    {
      id: "itmo-review",
      period: "Ноябрь 2024 — январь 2025",
      start: "2024-11",
      end: "2025-01",
      track: "work",
      kind: "Работа",
      organization: "ИТМО, Санкт-Петербург",
      role: "Лаборант",
      description: "Проводил ревью и оценку GitHub-репозиториев лаборатории: разбирался в коде проектов и писал для них тесты.",
      tags: [
        { label: "Ревью репозиториев", category: "contribution" },
        { label: "GitHub", category: "technology" },
        { label: "Тестирование", category: "practice" },
      ],
    },
    {
      id: "itmo-education",
      period: "2024 — 2028",
      start: "2024-09",
      end: "2028-06",
      track: "education",
      kind: "Образование",
      organization: "Университет ИТМО",
      role: "Прикладная информатика",
      description: "Изучаю алгоритмы, системное программирование, математику и проектирование программных систем.",
      tags: [
        { label: "Алгоритмы", category: "practice" },
        { label: "Системное программирование", category: "practice" },
        { label: "Прикладная информатика", category: "domain" },
      ],
      status: "Обучаюсь",
    },
  ],
};
