import type { ContactContent } from "../schema";

export const contact: ContactContent = {
  label: "Contact",
  title: { lead: "Let’s discuss", accent: "a backend challenge" },
  description: "I’m considering full-time roles, internships, and project work. I’m open to relocation and business travel.",
  form: {
    nameLabel: "Your name",
    namePlaceholder: "How should I address you?",
    emailLabel: "Reply email",
    emailPlaceholder: "you@example.com",
    messageLabel: "Message",
    messagePlaceholder: "Tell me what you’d like to discuss",
    submitLabel: "Send message",
    sendingLabel: "Sending…",
    requiredError: "This field is required.",
    invalidEmailError: "Enter a valid email address.",
    tooLongError: "The maximum length has been exceeded.",
    validationFailed: "Check your details and try again.",
    successMessage: "Message sent. Thank you!",
    deliveryError: "Could not send your message. Try again or contact me directly.",
    rateLimitError: "Too many attempts. Wait a little and try again.",
    unavailableError: "The form is temporarily unavailable. Please email me directly.",
  },
  status: "Open to opportunities",
  responseTime: "I usually reply within a day",
  phone: "+7 (980) 389-23-83",
  phoneLabel: "Call me",
  email: "asmorr@yandex.ru",
  emailLabel: "Send an email",
  github: "https://github.com/asmorr",
  githubLabel: "View GitHub",
  location: "Saint Petersburg, Russia",
  locationLabel: "Location",
};
