import type { ContactContent } from "../schema";

export const contact: ContactContent = {
  label: "Contact",
  title: { lead: "Let’s discuss", accent: "a backend challenge" },
  description: "I’m considering full-time roles, internships, and project work. I’m open to relocation and business travel.",
  status: "Open to opportunities",
  responseTime: "I usually reply within a day",
  phone: "+7 (980) 389-23-83",
  phoneLabel: "Call me",
  email: "asmorr@yandex.ru",
  emailLabel: "Send an email",
  github: "https://github.com/asmorr",
  githubLabel: "View GitHub",
  location: "Saint Petersburg, Russia",
  locationLabel: "Location",
  form: {
    nameLabel: "Name",
    namePlaceholder: "How should I address you?",
    emailLabel: "Reply email",
    emailPlaceholder: "name@example.com",
    messageLabel: "Message",
    messagePlaceholder: "Tell me about the role, team, or project",
    submitLabel: "Send message",
    requiredError: "Complete this field",
    emailError: "Enter a valid email",
    messageLengthError: "Keep the message under 2,000 characters",
    unavailableMessage: "The form is ready, but delivery is coming later. For now, email me directly.",
  },
};
