import type { TimelineContent } from "../schema";

export const timeline: TimelineContent = {
  label: "Journey",
  title: "Experience and education",
  intro: "Professional and academic work shaping how I approach backend engineering.",
  items: [
    {
      id: "itmo-research",
      period: "March 2025 — present",
      start: "2025-03",
      end: null,
      track: "work",
      kind: "Work",
      organization: "ITMO University, Saint Petersburg",
      role: "Lab Assistant / Backend Developer",
      description: "I began with database and backend work for a library framework analysing scientific publications. In January 2026, it joined adjacent teams as a microservice platform for collecting, processing, and validating data; I own the canonicalisation service.",
      tags: [
        { label: "Canonicalisation service", category: "contribution" },
        { label: "Python", category: "technology" },
        { label: "Microservices", category: "practice" },
        { label: "Scientific data", category: "domain" },
      ],
      status: "Current",
    },
    {
      id: "lkey",
      period: "December 2024 — May 2025",
      start: "2024-12",
      end: "2025-05",
      track: "work",
      kind: "Project work",
      organization: "Lkey Studio",
      role: "Backend Developer",
      description: "Designed the server architecture for an online lighting store from scratch, including its REST API, data model, and caching layer.",
      tags: [
        { label: "Built from scratch", category: "contribution" },
        { label: "Django REST Framework", category: "technology" },
        { label: "PostgreSQL", category: "technology" },
        { label: "Redis", category: "technology" },
      ],
    },
    {
      id: "itmo-review",
      period: "November 2024 — January 2025",
      start: "2024-11",
      end: "2025-01",
      track: "work",
      kind: "Work",
      organization: "ITMO University, Saint Petersburg",
      role: "Lab Assistant",
      description: "Reviewed and assessed the laboratory’s GitHub repositories, worked through project code, and wrote tests for them.",
      tags: [
        { label: "Repository review", category: "contribution" },
        { label: "GitHub", category: "technology" },
        { label: "Testing", category: "practice" },
      ],
    },
    {
      id: "itmo-education",
      period: "2024 — 2028",
      start: "2024-09",
      end: "2028-06",
      track: "education",
      kind: "Education",
      organization: "ITMO University",
      role: "Applied Computer Science",
      description: "Studying algorithms, systems programming, mathematics, and software system design.",
      tags: [
        { label: "Algorithms", category: "practice" },
        { label: "Systems Programming", category: "practice" },
        { label: "Applied Computer Science", category: "domain" },
      ],
      status: "Ongoing",
    },
  ],
};
